#
# configuration for risk analysis for inundation
# author : Phisan Santitamnont
#
# topo-level key-value pairs
REGION_PROV = 'Phuket|Ranong|Phangnga|Krabi|Trang|Satun'

# GLOBAL Range 
GLOBAL_RANGE  = [ [0.5,10] , [5,1000] ]  #  MSL and WorldPop , grid 100mx100m   
[MINMAX]  # MSL_min, MSL_max (grid 30mx30m), Popu_min, Popu_max (grid100mx100m)
DEFAULT  = [ [0.5,10] , [5,1000] ]
Phuket   = [ [0.5,10], [25,500]  ]  #  MSL and WorldPop , grid 100mx100m
Phangnga = [ [0.5,10], [5,500]  ]   #  MSL and WorldPop , grid 100mx100m

[DBSCAN] # DEM_EPS_m, DEM_MIN_pnt,  POPU_EPS_m, POPU_MIN_pnt 
DEFAULT =  [   [ 120, 30 ],              [ 300, 16 ] ]  
Phangnga = [   [ 130, 30 ],              [ 200, 10 ] ]
#       DEM  MIN/pnt 179pnt=100rai     POPU  MIN/pnt 16pnt=100rai 
  
